### ISSUE TITLE
Failed to activate the vim-surround package

### ISSUE THREAD

**Issue by protoiyer** [gepoch/vim-surround#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.5.0

### Stack Trace

Failed to activate the vim-surround package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
  at /Users/suresh.iyer/.atom/packages/vim-surround/lib/surround.coffee:27:14
  at Surround.registerPairs (/Users/suresh.iyer/.atom/packages/vim-surround/lib/surround.coffee:52:9)
  at /Users/suresh.iyer/.atom/packages/vim-surround/lib/surround.coffee:1:1
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:544:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:126:21)
  at Surround.activate (/Users/suresh.iyer/.atom/packages/vim-surround/lib/surround.coffee:16:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -30:48.7 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
vim-surround, v0.5.0

# Dev
No dev packages
```

**Comment by gepoch** [comment]
Hmm.. Do you have a trailing comma in the settings for the surround module, possibly?

Anyways, I've release 0.5.1 to cover for the possible issue that may be causing this. Let me know how it works for you!

**Comment by protoiyer** [comment]
I didn't make any changes to the settings, @gepoch. I will try uninstalling and reinstalling.

**Comment by gepoch** [comment]
Did 0.5.1 fix things for you?

**Comment by protoiyer** [comment]
Yes, it did. I just uninstalled 0.5.0 and installed 0.5.1. I haven't tested
the surround features yet. Will report back in case there are any issues.
Thanks.

On Tue, Apr 14, 2015 at 8:44 PM, George Marchin <notifications@github.com>
wrote:

> Did 0.5.1 fix things for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gepoch/vim-surround/issues/15#issuecomment-92899027>.
>



-- 
Suresh Iyer
+91-98402-78798 | protoiyer@gmail.com
---
In the long run men hit only what they aim at - Henry David Thoreau

**Comment by shemerey** [comment]
New problems with latest Atom 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.6.0


### Stack Trace

Failed to activate the vim-surround package

```
At Cannot read property 'add' of undefined

TypeError: Cannot read property 'add' of undefined
    at Surround.module.exports.Base.createPairBindings (/Users/zork/.atom/packages/vim-surround/lib/command/base.coffee:66:46)
    at Surround.module.exports.Base.registerPair (/Users/zork/.atom/packages/vim-surround/lib/command/base.coffee:44:14)
    at Surround.module.exports.Base.registerPairs (/Users/zork/.atom/packages/vim-surround/lib/command/base.coffee:31:16)
    at Surround.Base (/Users/zork/.atom/packages/vim-surround/lib/command/base.coffee:11:12)
    at new Surround (/Users/zork/.atom/packages/vim-surround/lib/command/surround.coffee:16:38)
    at /Users/zork/.atom/packages/vim-surround/lib/vim-surround.coffee:36:23
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at Object.module.exports.activate (/Users/zork/.atom/packages/vim-surround/lib/vim-surround.coffee:24:44)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "disabledPackages": [
      "atom-ctags",
      "file-type-icons",
      "tabs",
      "tree-view"
    ]
  },
  "vim-surround": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.7
language-viml, v0.2.0
project-manager, v1.15.8
rspec-snippets, v0.4.0
tomorrow-night-eighties-syntax, v0.6.1
vim-mode, v0.51.0
vim-surround, v0.6.0

# Dev
No dev packages
```

**Comment by gepoch** [comment]
Indeed. Seems to have broken at 206.

I'll try to get a fix out this morning. Thanks for the bug report.

**Comment by jtheoof** [comment]
This issue resurfaced for me today, after upgrade to atom 1.9.

```
Failed to activate the vim-surround package: Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jattali/.atom/packages/vim-surround/lib/command/selector.coffee:4:46)
    at Object.<anonymous> (/Users/jattali/.atom/packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jattali/.atom/packages/vim-surround/lib/command/delete.coffee:4:12)
    at Object.<anonymous> (/Users/jattali/.atom/packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by jeffling** [comment]
I also have this. I also still have this. It's not fixed. 

[Enter steps to reproduce below:]

1. Try to install the package. 

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.8.1


### Stack Trace

Failed to activate the vim-surround package

```
At Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/command/selector.coffee:4:46)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/command/delete.coffee:4:12)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/vim-surround.coffee:4:10)
    at Object.<anonymous> (/Users/jeff/.atom/packages/vim-surround/lib/vim-surround.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:718:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:460:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
     -0:25 clipboard-history:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:17.9.0 settings-view:open (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:13.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "Rdio",
      "autocomplete"
    ],
    "projectHome": "/Users/jeff/Work",
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-ternjs, v0.15.0 (active)
clipboard-history, v0.6.6 (active)
emmet, v2.4.3 (active)
erb-helper, v1.0.1 (inactive)
git-plus, v5.17.1 (inactive)
git-time-machine, v1.5.3 (inactive)
go-to-view, v0.3.0 (active)
linter, v1.11.16 (active)
linter-less, v2.6.0 (active)
linter-ruby, v1.2.2 (active)
narrow, v0.6.0 (active)
open-this, v0.2.0 (inactive)
paner, v0.4.0 (inactive)
rails-latest-migration, v1.1.6 (inactive)
rails-partials, v0.9.2 (inactive)
rails-transporter, v1.6.5 (inactive)
react, v0.16.0 (active)
rubocop-auto-correct, v1.5.1 (inactive)
solarized-dark-ui, v0.3.1 (active)
vim-mode-plus, v0.57.0 (active)
vim-surround, v0.8.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by gepoch** [comment]
@jeffling You're using vim-mode-plus. vim-mode-plus implements its own surround commands, so vim-surround isn't necessary! There's a bit of up-front configuration, but it works great. See here for an example keymap setup:  https://github.com/t9md/dotfiles/blob/master/atom/keymap.cson#L208

**Comment by jeffling** [comment]
Thank you, @gepoch.
