### ISSUE TITLE
Failed to load the vim-surround package

### ISSUE THREAD

**Issue by mavenave** [gepoch/vim-surround#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.7.2

### Stack Trace

Failed to load the vim-surround package

```
At Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/command/selector.coffee:2:46)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/command/selector.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/command/delete.coffee:4:12)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/command/delete.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/vim-surround.coffee:4:10)
  at Object.<anonymous> (/home/maverick/.dotfiles/atom.symlink/packages/vim-surround/lib/vim-surround.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at /usr/share/atom/resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
 11x -2:05.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:00.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:00.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:40.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -1:35.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:33.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:33.8.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
  3x -1:24 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:23.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:23.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:18.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:14.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:14.1.0 open-on-github:file (atom-text-editor.editor)
     -1:04.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:42.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".bundle",
      ".git",
      "log",
      "repositories",
      "tmp",
      "vendor"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "hideGitIgnoredFiles": true,
    "disabledPackages": [
      "background-tips",
      "exception-reporting",
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
pigments, v0.8.0
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by gepoch** [comment]
Does a reload fix this? I believe we might be looking at https://github.com/gepoch/vim-surround/issues/21

**Comment by samkcarlile** [comment]
I'm having the same problem.  A reload shows the same error

**Comment by gepoch** [comment]
Do you have vim-mode installed in your atom, @samkcarlile?

**Comment by samkcarlile** [comment]
How did I miss that... Sorry and thanks!

**Comment by gepoch** [comment]
@samkcarlile no prob. I'd like to get this sorted out anyways! Thanks for the response.

**Comment by ssfrr** [comment]
Hmm, I'm seeing this and a restart does not help. I even tried shutting Atom down, uninstalling and re-installing vim-mode and vim-surround using `apm`, and then restarting.

**Comment by KabbAmine** [comment]
Same thing here but with [vim-mode-next](https://github.com/bronson/vim-mode-next).

The strange thing is that when I have vim-mode-next + vim-mode disabled, there is no issue :confused:

**Comment by gepoch** [comment]
Hey. Try v0.8.0, vim-next-mode people! #28

**Comment by KabbAmine** [comment]
Vim-mode uninstalled and no more issue after #28 , so :+1:
