### ISSUE TITLE
Failed to load the vim-surround package

### ISSUE THREAD

**Issue by burgleaf** [gepoch/vim-surround#35]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.8.1
### Stack Trace

Failed to load the vim-surround package

```
At Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/command/selector.coffee:4:46)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/command/delete.coffee:4:12)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/vim-surround.coffee:4:10)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-surround/lib/vim-surround.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
javascript-snippets, v1.0.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by theamazingfedex** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.8.1


### Stack Trace

Failed to load the vim-surround package

```
At Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/command/selector.coffee:4:46)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/command/delete.coffee:4:12)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/vim-surround.coffee:4:10)
    at Object.<anonymous> (/Users/daniwood/.atom/packages/vim-surround/lib/vim-surround.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:516:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  7x -6:55.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -6:52.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:53.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:53.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:50.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:51.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:50.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:48.9.0 core:delete (atom-text-editor.editor.is-focused)
     -2:48 core:move-down (atom-text-editor.editor.is-focused)
     -2:47.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:46.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:46.2.0 core:delete (atom-text-editor.editor.is-focused)
     -2:44.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:43.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:35.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:53 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-react-preview, v1.2.1
atom-ternjs, v0.12.2
auto-update-packages, v1.0.0
autocomplete-modules, v1.3.1
editorconfig, v1.2.2
language-babel, v2.7.3
linter, v1.11.3
linter-eslint, v5.2.7
linter-flow, v4.1.0
nuclide-flow, v0.0.35
pigments, v0.19.5
react, v0.12.10
react-es6-snippets, v0.3.0
react-snippets, v0.3.0
redux-snippets, v0.2.1
sync-settings, v0.6.0
term3, v0.21.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by li-xinyang** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0-beta8
**System**: Ubuntu 14.04.3
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package, v0.8.1


### Stack Trace

Failed to load the vim-surround package

```
At Cannot find module 'vim-mode/lib/text-objects'

Error: Cannot find module 'vim-mode/lib/text-objects'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/command/selector.coffee:4:46)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/command/delete.coffee:4:12)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/vim-surround.coffee:4:10)
    at Object.<anonymous> (/home/li-xinyang/.atom/packages/vim-surround/lib/vim-surround.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom-beta/resources/app.asar/src/package.js:720:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "welcome"
    ]
  },
  "vim-surround": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
docblockr, v0.7.3
hyperclick, v0.0.35
js-hyperclick, v1.4.1
linter, v1.11.3
linter-jshint, v2.0.3
linter-pep8, v1.2.1
minimap, v4.21.0
pigments, v0.24.5
project-manager, v2.7.6
terminal-plus, v0.14.5
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by lukeorland** [comment]
This is still happening with Atom Version: 1.7.1.

**Comment by jkrmr** [comment]
I encountered this error when I tried installing vim-surround after only installing vim-mode-plus. 

Installing vim-mode resolved it for me.

**Comment by lacostenycoder** [comment]
Just use this https://atom.io/packages/vim-mode-plus-keymaps-for-surround with vim-mode-plus

**Comment by Cphoenix** [comment]
> Just use this https://atom.io/packages/vim-mode-plus-keymaps-for-surround with vim-mode-plus

Have that already, tried reinstalling everything, with vim-surround last, still failed.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [vim-surround](https://github.com/gepoch/vim-surround) package 0.8.1


### Stack Trace

Failed to load the vim-surround package

```
At Cannot find module 'undefined/lib/text-objects'

Error: Cannot find module 'undefined/lib/text-objects'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/vim-surround/lib/command/selector.coffee:4:46)
    at /packages/vim-surround/lib/command/selector.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/vim-surround/lib/command/delete.coffee:4:12)
    at /packages/vim-surround/lib/command/delete.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/vim-surround/lib/vim-surround.coffee:4:10)
    at /packages/vim-surround/lib/vim-surround.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -6:12.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -4:24.2.0 settings-view:open (input.hidden-input)
 10x -4:15.9.0 core:backspace (input.hidden-input)
  2x -3:39.1.0 core:confirm (input.hidden-input)
  2x -1:12.2.0 core:backspace (input.hidden-input)
     -1:09.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

*NOTE:* Many of these are disabled. Bug me if you need clarification.

```
advanced-open-file 0.16.6 
atom-alignment 0.12.1 
atom-beautify 0.29.19 
atom-css-clean 2.19.6 
atom-css-comb 3.1.0 
atom-ctags 5.0.0 
atom-dark-fusion-syntax 2.2.0 
atom-formatter-jsbeautify 1.1.2 
atom-mermaid 3.1.0 
atom-reverser 2.6.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
block-comment-lines 0.2.4 
busy-signal 1.3.0 
case-switch 2.2.4 
change-case 0.6.5 
color-picker 2.2.5 
compare-files 0.8.0 
css-clean 2.19.0 
css-snippets 1.1.0 
ctags-status 1.3.7 
docblockr 0.9.4 
emmet 2.4.3 
emmet-simplified 2.5.0 
file-icons 2.1.3 
file-types 0.5.5 
git-diff-details 1.4.0 
git-log 0.4.1 
git-time-machine 1.5.9 
goto 1.8.3 
guess-indent 0.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
imdone-atom undefined 
imdone-atom-github 0.1.11 
indent-guide-improved 1.4.12 
intentions 1.1.2 
jekyll 2.0.0 
kerbal-config 0.4.1 
kite 0.21.0 
language-liquid 0.5.1 
language-lua 0.9.11 
language-markdown 0.20.0 
language-mediawiki 2.2.0 
language-plantuml 0.2.0 
language-scheme 1.4.0 
language-tmux 0.4.0 
lines 0.13.1 
linter 2.1.4 
linter-javac 1.9.4 
linter-js-standard 3.9.0 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-markdown 4.0.0 
linter-pylama 0.8.16 
linter-python-pep8 0.2.0 
linter-sass-lint 1.7.4 
linter-shellcheck 1.4.4 
linter-solidity 0.5.0 
linter-tidy 2.3.1 
linter-ui-default 1.2.3 
markdown-preview-enhanced 0.10.12 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.6 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-wrap-guide 0.28.3 
on-the-rocks 2.1.0 
one-dark-vivid-syntax 1.7.1 
open-recent 5.0.0 
pandoc-convert 1.1.0 
pigments 0.39.1 
plantuml-viewer 0.7.1 
project-manager 3.3.4 
project-plus 0.9.0 
python-tools 0.6.9 
release-notes 0.53.0 
script 3.14.1 
slim-dark-ui 0.12.0 
split-diff 1.3.0 
symbol-gen 1.3.1 
sync-settings 0.8.1 
synced-sidebar 0.4.3 
todo-show 1.11.0 
vim-mode-plus 0.89.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-selected-text 0.9.0 
vim-mode-plus-subword-movement 0.2.2 
vim-surround 0.8.1 
```
```

**Comment by gepoch** [comment]
Hey @Cphoenix  vim-surround does not support vim-mode-plus. This plugin added surround features to vim-mode, which is now deprecated in favor of vim-mode-plus which has built-in surround-like tools. You don't need this package if you're using vim-mode-plus.
